apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot1
  name: spring-controller1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot1
    spec:
      containers:
      - image: ${REPOSITORY_TAG}
        name: springboot1
        ports:
        - name: springboot1
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot1
  name: springboot1
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot1
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo1
  name: mongo-controller1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo1
    spec:
      containers:
      - image: mongo
        name: mongo1
        ports:
        - name: mongo1
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage1
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage1
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo1
  name: mongo1
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo1
